### PR TITLE
7 optional sax validation

### LINKED ISSUE #7: Incorrectly formats XML files with DOCTYPE statements
See RENCI-NRIG/orca5#176

[Example diff](https://github.com/RENCI-NRIG/orca5/commit/0ff070ee9df1293f74b9f16e26f2b33f0f38a71e#diff-6d0ca63a6a8548b23def2bbe58b2cbfd)
``` 
-<!DOCTYPE project [
-<!ENTITY deps SYSTEM “ant/deps.xml”>
-<!ENTITY core SYSTEM “ant/core.xml”>
-<!ENTITY packages SYSTEM “ant/packages.xml”>
-<!ENTITY tests SYSTEM “ant/tests.xml”>
-]>

+<!DOCTYPE project> 
+<!--ENTITY core SYSTEM “ant/core.xml”--> 
+<!--ENTITY packages SYSTEM “ant/packages.xml”--> 
+<!--ENTITY tests SYSTEM “ant/tests.xml”-->
+ ]&gt;
```

### PR DESCRIPTION
**Pull request by hinchliff**
Fixes #7, adding preference to make SAX validation optional, with default of WARN.

### CODE REVIEW

**Comment by jam01** [comment]
This looks good, thanks @hinchliff !

@ctubbsii any thoughts?

File: src/main/java/net/revelc/code/formatter/xml/lib/FormattingPreferences.java [hunk 1]
```diff
@@ -16,11 +16,16 @@
 package net.revelc.code.formatter.xml.lib;
 
 public class FormattingPreferences {
+    public static final String IGNORE = "IGNORE";
+    public static final String WARN = "WARN";
+    public static final String FAIL = "FAIL";
```
Comment (ctubbsii) [inline src/main/java/net/revelc/code/formatter/xml/lib/FormattingPreferences.java]: Why not use enum here instead of String constants?

File: src/main/java/net/revelc/code/formatter/xml/lib/FormattingPreferences.java [hunk 2]
```diff
@@ -81,4 +86,14 @@ public void setSplitMultiAttrs(Boolean setSplitMultiAttrs) {
...
             this.splitMultiAttrs = setSplitMultiAttrs;
     }
+
+    public String getSaxValidation() { return saxValidation; }
+
+    public void setSaxValidation(String saxValidation) {
+        if (saxValidation.equals(IGNORE) || saxValidation.equals(FAIL)) {
+            this.saxValidation = saxValidation;
+        } else {
+            this.saxValidation = WARN;
```
Comment (ctubbsii) [inline src/main/java/net/revelc/code/formatter/xml/lib/FormattingPreferences.java]: Defaulting to WARN silently even when receiving an unrecognized argument is probably not a very friendly API behavior. It should throw `IllegalArgumentException` if it doesn't recognize the argument.

File: src/main/java/net/revelc/code/formatter/xml/lib/XmlDocumentFormatter.java [hunk 3]
```diff
@@ -114,7 +116,11 @@ private void validateWellFormedness(String documentText) {
             reader.setErrorHandler(errorHandler);
             reader.parse(new InputSource(new StringReader(documentText)));
         } catch (Exception exception) {
-            throw new IllegalArgumentException(exception);
+            if (prefs.getSaxValidation().equals(FormattingPreferences.WARN)) {
+                System.out.println(exception.getMessage());
```
Comment (ctubbsii) [inline src/main/java/net/revelc/code/formatter/xml/lib/XmlDocumentFormatter.java]: Are there other places where the `System.out` is called directly? I wouldn't recommend calling `System.out` directly, over the use of a system logger, or at the very least, a global PrintStream object that is set to System.out at startup, so it can be managed in one place.

File: src/main/java/net/revelc/code/formatter/xml/lib/FormattingPreferences.java (hunk 1 above)
Comment (hinchliff) [reply src/main/java/net/revelc/code/formatter/xml/lib/FormattingPreferences.java]: Yeah, I had thought about using enum, and that does seem to make more sense.  When I went looking for examples in the Java formatter being used in `formatter-maven-plugin`, it seemed to be using Strings for everything, so I went with that.  e.g. https://github.com/eclipse/eclipse.jdt.core/search?l=Java&q=brace_position_for_annotation_type_declaration

Happy to revisit, just let me know.

File: src/main/java/net/revelc/code/formatter/xml/lib/FormattingPreferences.java (hunk 2 above)
Comment (hinchliff) [reply src/main/java/net/revelc/code/formatter/xml/lib/FormattingPreferences.java]: Good point.  I will fix this.

File: src/main/java/net/revelc/code/formatter/xml/lib/XmlDocumentFormatter.java (hunk 3 above)
Comment (hinchliff) [reply src/main/java/net/revelc/code/formatter/xml/lib/XmlDocumentFormatter.java]: I didn't see a logger, and there was a previous usage of using `System.out`, so that's what I went with: https://github.com/revelc/xml-formatter/blob/bd9e761e94ba7b02a6fb0d22f8ff7e6008ccb10e/src/main/java/net/revelc/code/formatter/xml/lib/XmlDocumentFormatter.java#L102

Also happy to revisit this choice, but it might be a separate issue?

**Comment by hinchliff** [comment]
@ctubbsii 

>Once released with this feature, what is the plan to expose these options to formatter-maven-plugin's configuration, if any? Will this require new maven plugin options to take advantage of this?

The new option would be exposed in `formatter-maven-plugin` through this config file: 
https://github.com/revelc/formatter-maven-plugin/blob/master/src/main/resources/formatter-maven-plugin/eclipse/xml.properties

File: src/main/java/net/revelc/code/formatter/xml/lib/FormattingPreferences.java (hunk 1 above)
Comment (ctubbsii) [reply src/main/java/net/revelc/code/formatter/xml/lib/FormattingPreferences.java]: I'm not really sure why they used Strings in their code everywhere... perhaps to make it easier to parse configuration files without converting keys in config files with `Enum.valueOf(...)`? Not sure. I'll leave it to you to decide which is best.

File: src/main/java/net/revelc/code/formatter/xml/lib/XmlDocumentFormatter.java (hunk 3 above)
Comment (ctubbsii) [reply src/main/java/net/revelc/code/formatter/xml/lib/XmlDocumentFormatter.java]: At the very least, it should use System.err for the warning so the caller can filter out STDERR.

**Comment by ctubbsii** [comment]
> @ctubbsii
> 
> > Once released with this feature, what is the plan to expose these options to formatter-maven-plugin's configuration, if any? Will this require new maven plugin options to take advantage of this?
> 
> The new option would be exposed in `formatter-maven-plugin` through this config file:
> https://github.com/revelc/formatter-maven-plugin/blob/master/src/main/resources/formatter-maven-plugin/eclipse/xml.properties

I see. So, no change in the formatter-maven-plugin is needed, except to update to the newer version of xml-formatter. Excellent!

File: src/main/java/net/revelc/code/formatter/xml/lib/FormattingPreferences.java (hunk 1 above)
Comment (hinchliff) [reply src/main/java/net/revelc/code/formatter/xml/lib/FormattingPreferences.java]: I won't try to pretend I know which way is better here.  If you don't have an objection to leaving it as String, then I will just keep it this way.

**Comment by hinchliff** [comment]
@ctubbsii 

Sorry for the delay in adding these little fixes.  Let me know if you need anything else.

Thanks.

**Comment by ctubbsii** [comment]
FWIW, it's okay to squash commits when you merge. It can make for a cleaner git history, and you can always keep your original branch, if you need the added detail (which is unlikely). Your choice.
